@startuml
    hide footbox
    
    actor Membre
    participant Protubes << System >>

    Membre -> Protubes : demandeFormulaire(connexion)
    Protubes -> Membre : returnFormulaire
    Membre -> Protubes : requeteConnexion(email,password)

    alt reussie
        Protubes -> Membre : connexion reussie
    else echoue
        Protubes -> Membre : Connexion refuse
        alt membre not exist
            Protubes --> Membre : Message d'inscription
        else compte not actif
            Protubes --> Membre : Message de validation mail inscription
        end
    end
@enduml