@startuml
    hide footbox
    
    actor Membre
    participant Protubes << System >>

    Membre -> Protubes : demandeFormulaire(inscription)
    Protubes -> Membre : returnFormulaire
    Membre -> Protubes : requeteInscription(informations)

    alt inscription valide
        Protubes --> Membre : Message de validation du compte par mail
    else inscription refuse
        Protubes --> Membre : Message d'echec information exist dans DataBase
        'Protubes -> Membre : Redirection formulaire(connexion)
    end

@enduml